apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  type: kv-v2
  mount: secret
  path: monitoring/grafana
  destination:
    name: grafana-admin-credentials
    create: true
  refreshAfter: 1h
  vaultAuthRef: monitoring-vault-auth
