apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-backup
  namespace: argocd
  annotations:
    # Deploy after Vault is ready
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Programmer-Network/argocd-app-of-apps.git
    targetRevision: main
    path: manifests/cluster/vault-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  revisionHistoryLimit: 10
