apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-r2-secret
  namespace: longhorn-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: longhorn-r2
  refreshAfter: 1h
  destination:
    name: r2-longhorn-secret
    create: true
    overwrite: true
