apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - networkpolicy.yaml
  - rbac.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - vault-secrets.yaml
