apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-backup-r2
  namespace: vault
spec:
  vaultAuthRef: vault-auth-kubernetes
  mount: secret
  type: kv-v2
  path: longhorn-r2
  destination:
    name: vault-backup-r2
    create: true
    overwrite: true
    type: Opaque
  hmacSecretData: true
