apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-kubernetes
  namespace: vault
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-backup-role
    serviceAccount: vault-backup
    tokenExpirationSeconds: 600
  vaultConnectionRef: vault-connection
