apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: cert-manager/cloudflare
  refreshAfter: 1h
  destination:
    name: cloudflare-api-token-secret
    create: true
    overwrite: true
